name: IronBlockElevator
version: ${project.version}
main: com.kubota6646.ironblockelevator.IronBlockElevator
api-version: 1.19
author: kubota6646
description: A plugin that enables iron block elevators
website: https://github.com/kubota6646/Iron-Block-Elevator

commands:
  ironblockelevator:
    description: Main command for Iron Block Elevator
    usage: /<command> [reload]
    aliases: [ibe]
